### ISSUE TITLE
Extend to keywords in code?

### ISSUE THREAD

**Issue by abp** [cldwalker/lein-spell#2]
Just a quick idea-dump and haven't found something like that in the readme:

Couldn't we check keywords in code using this?

Rare keywords could gain relevance, keywords with approximate occurences gain even more. This would probably carry mispellings far enough up in the list.

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 14 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/lein-spell#2). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by cldwalker** [comment]
By keywords you mean clojure keywords, right? From the codebases I've run this on, that hasn't been a large source of false positives. If you have a code base that would benefit from this check I'd be interested to see it. 

The biggest source of false positives right now is code blocks in markdown files.

**Comment by cldwalker** [comment]
Closing as I see this as a lot of work for little benefit - lein-spell doesn't currently parse all of your clojure code, just your docstrings

**Comment by abp** [comment]
Yes, you are right on this one. Just saw some bug fix commits to libraries where keywords had typos and put the idea in here.
